apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production-demo-app
  namespace: argocd
spec:
  destination:
    namespace: prod  # ← ИЗМЕНЯЕМ С default НА prod
    server: https://kubernetes.default.svc
  source:
    path: k8s-manifests/base/demo-app
    repoURL: https://github.com/shahat112/k8s-production-config.git
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
