apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-with-metrics
  namespace: demo-apps
  labels:
    app: apache-with-metrics
    app-type: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache-with-metrics
  template:
    metadata:
      labels:
        app: apache-with-metrics
        app-type: demo
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9117"
    spec:
      containers:
      - name: apache
        image: httpd:alpine
        ports:
        - containerPort: 80
      - name: apache-exporter
        image: lusotycoon/apache-exporter
        args:
          - '--scrape_uri=http://localhost:80/server-status?auto'
        ports:
        - containerPort: 9117
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: apache-with-metrics
  namespace: demo-apps
  labels:
    app: apache-with-metrics
    app-type: demo
spec:
  selector:
    app: apache-with-metrics
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: metrics
    port: 9117
    targetPort: 9117
