apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-server
    spec:
      serviceAccountName: argocd-server
      containers:
      - name: argocd-server
        image: quay.io/argoproj/argocd:v3.2.2
        imagePullPolicy: IfNotPresent
        # ПРАВИЛЬНАЯ команда для argocd-server
        command: ["/usr/local/bin/argocd-server"]
        args:
        - "--insecure"               # Разрешаем HTTP
        - "--staticassets"           # Встроенные статические файлы
        - "/shared/app"              # Путь к статике
        env:
        - name: ARGOCD_SERVER_INSECURE
          value: "true"
        - name: ARGOCD_SERVER_STATICASSETS
          value: "/shared/app"
        - name: ARGOCD_REDIS_ADDRESS
          value: "argocd-redis.argocd.svc.cluster.local:6379"
        - name: ARGOCD_REPO_SERVER
          value: "argocd-repo-server.argocd.svc.cluster.local:8081"
        - name: ARGOCD_DEX_SERVER
          value: "http://argocd-dex-server.argocd.svc.cluster.local:5556"
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8083
          name: metrics
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 40
          periodSeconds: 10
          timeoutSeconds: 5
        volumeMounts:
        - name: static-files
          mountPath: /shared/app
          readOnly: true
      volumes:
      - name: static-files
        emptyDir: {}
