apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-server
    spec:
      containers:
      - name: argocd-server
        image: argoproj/argocd:v2.9.5
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        # ИСПРАВЛЕННЫЕ ПРОБЫ:
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 60  # Даем больше времени на старт
          periodSeconds: 30
          timeoutSeconds: 10       # Увеличиваем таймаут
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10       # Увеличиваем таймаут
          failureThreshold: 3
        env:
        - name: ARGOCD_SERVER_INSECURE
          value: "true"
        - name: ARGOCD_SERVER_ROOTPATH
          value: /
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
