apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production-demo-app
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/shahat112/k8s-production-config.git
    targetRevision: HEAD
    path: k8s-manifests/base/demo-app  # ПРАВИЛЬНЫЙ ПУТЬ!
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
