apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-demo-app
  namespace: prod
  labels:
    app: demo-app
    environment: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
      environment: production
  template:
    metadata:
      labels:
        app: demo-app
        environment: production
    spec:
      containers:
      # Основной контейнер nginx
      - name: nginx
        image: nginxinc/nginx-unprivileged:alpine
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: ENVIRONMENT
          value: "production"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 101
        command:
        - /bin/sh
        args:
        - -c
        - |
          mkdir -p /run /tmp/nginx /var/cache/nginx
          chown -R 101:101 /run /tmp/nginx /var/cache/nginx
          
          cat > /etc/nginx/nginx.conf << 'NGINX_CONF'
          user nginx;
          worker_processes auto;
          error_log /var/log/nginx/error.log warn;
          pid /tmp/nginx/nginx.pid;
          
          events {
              worker_connections 1024;
          }
          
          http {
              include /etc/nginx/mime.types;
              default_type application/octet-stream;
              
              log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                            '$status $body_bytes_sent "$http_referer" '
                            '"$http_user_agent" "$http_x_forwarded_for"';
              
              access_log /var/log/nginx/access.log main;
              
              sendfile on;
              keepalive_timeout 65;
              
              server {
                  listen 8080;
                  server_name localhost;
                  
                  location / {
                      root /usr/share/nginx/html;
                      index index.html index.htm;
                  }
                  
                  location /health {
                      add_header Content-Type application/json;
                      return 200 '{"status": "healthy", "environment": "production"}';
                  }
                  
                  # stub_status для экспортера
                  location /stub_status {
                      stub_status on;
                      access_log off;
                  }
                  
                  error_page 500 502 503 504 /50x.html;
                  location = /50x.html {
                      root /usr/share/nginx/html;
                  }
              }
          }
          NGINX_CONF
          
          exec nginx -g "daemon off;"
        volumeMounts:
        - name: nginx-run
          mountPath: /run
        - name: nginx-tmp
          mountPath: /tmp/nginx
        - name: nginx-cache
          mountPath: /var/cache/nginx
      
      # Экспортер для Prometheus
      - name: nginx-exporter
        image: nginx/nginx-prometheus-exporter:latest
        ports:
        - containerPort: 9113
          name: metrics
        args:
        - -nginx.scrape-uri=http://localhost:8080/stub_status
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 101
      
      volumes:
      - name: nginx-run
        emptyDir: {}
      - name: nginx-tmp
        emptyDir: {}
      - name: nginx-cache
        emptyDir: {}
