apiVersion: v1
kind: Service
metadata:
  name: prod-demo-app
  namespace: prod
  labels:
    app: demo-app
    environment: production
spec:
  selector:
    app: demo-app
    environment: production
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
