apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prod-demo-app
  namespace: prod
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: demo-app
      environment: production
  namespaceSelector:
    matchNames:
    - prod
  endpoints:
  - port: http
    interval: 30s
    path: /metrics
    scrapeTimeout: 10s
