apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prod-nginx-exporter
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: demo-app
  namespaceSelector:
    matchNames:
    - prod
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    scrapeTimeout: 30s
    honorLabels: true
