apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production-demo-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/shahat112/k8s-production-config.git
    targetRevision: HEAD
    path: k8s-manifests/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  info:
    - name: description
      value: Production Demo Application
    - name: url
      value: https://prod.demo-app.158.160.206.202.nip.io
